/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkersRouteImport } from './routes/workers'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as EvalRouteImport } from './routes/eval'
import { Route as IndexRouteImport } from './routes/index'

const WorkersRoute = WorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const EvalRoute = EvalRouteImport.update({
  id: '/eval',
  path: '/eval',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/eval': typeof EvalRoute
  '/training': typeof TrainingRoute
  '/workers': typeof WorkersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/eval': typeof EvalRoute
  '/training': typeof TrainingRoute
  '/workers': typeof WorkersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/eval': typeof EvalRoute
  '/training': typeof TrainingRoute
  '/workers': typeof WorkersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/eval' | '/training' | '/workers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/eval' | '/training' | '/workers'
  id: '__root__' | '/' | '/eval' | '/training' | '/workers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EvalRoute: typeof EvalRoute
  TrainingRoute: typeof TrainingRoute
  WorkersRoute: typeof WorkersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workers': {
      id: '/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof WorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eval': {
      id: '/eval'
      path: '/eval'
      fullPath: '/eval'
      preLoaderRoute: typeof EvalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EvalRoute: EvalRoute,
  TrainingRoute: TrainingRoute,
  WorkersRoute: WorkersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
