/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModelsIndexRouteImport } from './routes/models.index'
import { Route as ChatOwnerNameRouteImport } from './routes/chat.$owner.$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsIndexRoute = ModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatOwnerNameRoute = ChatOwnerNameRouteImport.update({
  id: '/chat/$owner/$name',
  path: '/chat/$owner/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/models/': typeof ModelsIndexRoute
  '/chat/$owner/$name': typeof ChatOwnerNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/models': typeof ModelsIndexRoute
  '/chat/$owner/$name': typeof ChatOwnerNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/models/': typeof ModelsIndexRoute
  '/chat/$owner/$name': typeof ChatOwnerNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/models/' | '/chat/$owner/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/models' | '/chat/$owner/$name'
  id: '__root__' | '/' | '/models/' | '/chat/$owner/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModelsIndexRoute: typeof ModelsIndexRoute
  ChatOwnerNameRoute: typeof ChatOwnerNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/': {
      id: '/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof ModelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$owner/$name': {
      id: '/chat/$owner/$name'
      path: '/chat/$owner/$name'
      fullPath: '/chat/$owner/$name'
      preLoaderRoute: typeof ChatOwnerNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModelsIndexRoute: ModelsIndexRoute,
  ChatOwnerNameRoute: ChatOwnerNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
